#!/usr/bin/env python

import psutil

mem = psutil.disk_usage("/")


mem_total = int(round(mem.total / (1024*1024*1024)))
mem_used = int(round(mem.used / (1024*1024*1024)))
color = "#558024"

if mem.percent > 90.0:
    color = "#FF0000"
elif mem.percent > 75.0:
    color = "#A54242"

output_line = "<span color='{}'>{}</span>/{}GB".format(
    color,
    mem_used,
    mem_total
)

print(output_line)
