#!/usr/bin/env sh

tmpbg=`mktemp /tmp/lockscreen.XXXXXXXX.png` || exit 1
scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
i3lock --textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e \
        --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 \
        --insidevercolor=0000001c \
        --ringwrongcolor=00000055 --insidewrongcolor=0000001c -i "$tmpbg"
rm "$tmpbg"
