#!/usr/bin/env python

import psutil

mem = psutil.virtual_memory()

mem_percent = int(round(mem.percent))
color = "#D8D8D8"

if mem.percent > 98.0:
    color = "#FF0000"
elif mem.percent > 80.0:
    color = "#A54242"
elif mem.percent > 50.0:
    color = "#F0C674"

total = mem.total / (1024.0 * 1024.0 * 1024.0)
used = (mem.total - mem.available) / (1024.0 * 1024.0 * 1024.0)
output_line = "<span color='{}'>{:.2f}/{:.2f}GB</span>".format(
    color,
    used,
    total
)

print(output_line)
