#!/usr/bin/env python

import psutil

mem = psutil.virtual_memory()

mem_percent = int(round(mem.percent))
color = "#D8D8D8"

if mem.percent > 98.0:
    color = "#FF0000"
elif mem.percent > 80.0:
    color = "#A54242"
elif mem.percent > 50.0:
    color = "#F0C674"

output_line = "<span color='{}'>{}%</span>".format(
    color,
    mem_percent
)

print(output_line)
