#!/usr/bin/env python

import os
import re
import argparse

parser = argparse.ArgumentParser(
    description='Generate a i3wm config file with environmental variables '
                'filled in')
parser.add_argument('input_file')
parser.add_argument('output_file')

args = parser.parse_args()

pattern = re.compile('\${env:(.*)}')
with open(args.input_file, 'r') as inf, open(args.output_file, 'w') as ouf:
    for i, line in enumerate(inf):
        for match in re.findall(pattern, line):
            if match not in os.environ:
                raise AttributeError('Environmental variable {} found on line'
                                     ' {} of file {} not defined.'.
                                     format(match, i + 1, args.input_file))

            line = line.replace('${{env:{}}}'.format(match), os.environ[match])

        ouf.write(line)
